### ISSUE TITLE
Add option: Only when under version control

### ISSUE THREAD

**Issue by eode** [atom/autosave#88] opened 2018-07-22 19:00 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

New feature:  Auto-save distinguishes between files that are under version control and those that aren't.

### Feature request

**Current Behavior:** No distinction is made between versioned and unversioned files.

**Desired Behavior:**
* New option in autosave config:
  [ ]  Only if file is under version control
* New behavior when option is checked: 
  If a file is not under version control, it is not autosaved.

**Comment by rsese** [comment] 2018-08-16 20:36
Thanks for the suggestion!  I think this is basically a duplicate of issues like https://github.com/atom/autosave/issues/64 where a selective autosave could be useful for some people.  As mentioned in https://github.com/atom/autosave/issues/64#issuecomment-344220940, this package exposes a service so that people can create packages to skip saving particular files so different options don't need to be added to autosave (also, the [package](https://github.com/aki77/atom-autosave-plus) mentioned in that issue might have the functionality you want?).

**Closed by rsese** 2018-08-16 20:36 UTC
