### ISSUE TITLE
auto save make lint's disappear

### ISSUE THREAD

**Issue by molikh** [atom/autosave#61] opened 2016-01-24 05:08 UTC
i'm using auto save for web front end development so set it's time 0.01  for showing fast to me with livereload.
problem comes up when i want to use it with lints, when auto save ( or any save methods) work lint's disappear  .
is there any way to solve that problem?

**Comment by lee-dohm** [comment] 2016-01-25 00:58
Can you be more specific as to what you mean by "use it with lints" and "lint's disappear"? Do you mean that you are using a linter tool of some sort and saving the file makes the lint error or warning messages disappear?

**Comment by molikh** [comment] 2016-02-01 10:47
in a css file & auto save is disable or time set is long enough: 
when i type p my linter package shows some lint can i use them.
but if auto save time set 1 sec lints will disappear fast and i can't use lints

**Comment by lee-dohm** [comment] 2016-02-01 19:06
Autosave doesn't save based on time. It doesn't even have a time setting:

<img width="790" alt="screen shot 2016-02-01 at 11 04 18 am" src="https://cloud.githubusercontent.com/assets/1038121/12727842/a090aeb0-c8d3-11e5-8e50-78bf632ed8ee.png">

From the `README`:

> Autosaves editor when they lose focus, are destroyed, or when the window is closed.

If you have another package that is autosaving files based on time, you might want to take a look at that package?

**Comment by molikh** [comment] 2016-02-02 14:42
my mistake . that's auto-save .
thanks.

**Comment by lee-dohm** [comment] 2016-02-02 17:54
It sounds like this issue is being caused by some other package or software, so I'm going to close this issue. Please let me know if I've misunderstood :grinning:

**Closed by lee-dohm** 2016-02-02 17:54 UTC
Labels: more-information-needed
