### ISSUE TITLE
Files are not saving on focus lost, only manually with cmd-s

### ISSUE THREAD

**Issue by christianstanfield** [atom/autosave#47] opened 2015-09-18 20:55 UTC
I'm on Atom 1.0.14 and Autosave 0.22.0 and file changes are not being saved to disk until I manually save. Autosave is enabled in config and the checkbox is set under settings. Just started happening today to me and a colleague.

**Comment by hljones** [comment] 2015-09-18 21:10
autosave stopped working for me  today 2015-09-18

I notice that the circle in tabs that indicates modification has stopped as well. Only see the x.

atom 1.0.14
autosave@0.22.0

Mac OS X 10.10.5 (14F27)

There was an update to XCode yesterday.

**Comment by 50Wliu** [comment] 2015-09-18 21:21
Confirmed.  Switching focus to a different tab does not save the file, presumably because the `modified` class is not present.  The modification dot (and class) not appearing is being tracked in #8849.

**Comment by christianstanfield** [comment] 2015-09-21 16:32
Looks like it's working again for me today, at least so far. Did an update come through that I missed?

**Comment by 50Wliu** [comment] 2015-09-21 19:42
@christianstanfield The bug seems to go away at times and then come back later, at least for me.

**Comment by christianstanfield** [comment] 2015-09-21 23:25
For me and a colleague it was working successfully all day, but that could have just been dumb luck. Wish I could help more, but I don't know the source code very well.

**Comment by JKGisMe** [comment] 2015-09-22 00:20
Not working for me. I closed and opened it. And then did "close and install update" and still not saving. I checked for more updates and there are none.

**Comment by vip9** [comment] 2015-09-22 11:00
For atom 1.0.14 and 1.0.15 - autosave does not work.

**Comment by vip9** [comment] 2015-09-23 10:12
Removing ~/.atom/storage/ makes autosave work again (1.0.15)

**Comment by 50Wliu** [comment] 2015-09-25 01:27
Should be fixed in Atom 1.0.18.  If it still happens, even after updating, please comment here!

**Closed by 50Wliu** 2015-09-25 01:27 UTC
Labels: bug
