### ISSUE TITLE
autosaving deleted, moved, renamed files

### ISSUE THREAD

**Issue by nruth** [atom/autosave#30] opened 2015-04-04 21:14 UTC
Bug: any open file that gets renamed or deleted will be ressurected by autosave.

This is a usability nightmare. Often results in editing the wrong file, or files that should have been deleted not getting deleted.

**Comment by balexand** [comment] 2015-05-18 15:28
This is a duplicate of #9. And there's a fix in #35.

**Comment by lee-dohm** [comment] 2015-05-18 15:32
Thanks @balexand. It is a duplicate. People interested in this should subscribe there for updates.

**Closed by lee-dohm** 2015-05-18 15:32 UTC
Labels: duplicate
